### ISSUE TITLE
Automatic disconnection？

### ISSUE THREAD

**Issue by Charles-Leo** [Niek/obs-web#58] opened 2021-06-15 04:08 UTC
Device1: iPad mini (5th generation)
Browser: safari
Device2: iPhone 12PM
Browser: safari
Recurrence success rate：100%

**Comment by Niek** [comment] 2021-06-15 04:19
Can you provide more details or screenshots? What is happening exactly?

**Comment by Charles-Leo** [comment] 2021-06-15 05:02
Thank you for your reply.
My OBS is running on Win10.


可用于iOS的myMail发送


2021年6月15日 星期二 +0800 12:20 发件人 ***@***.***  ***@***.***>:

**Comment by webdevisme** [comment] 2021-06-21 09:43
@Charles-Leo Please provide more information to the disconnection problem.

e.g.
When does it happen?
How often?

**Comment by Charles-Leo** [comment] 2021-06-22 06:45
Every time I open the client with safari on my iPad, enter the IP address and port number. The first connection can be Keep connected about 10 seconds, and then click connect again, and it will be disconnected immediately.
obs-websocket version: 4.9.0
If you have a mobile device, you can try the following to see if this problem occurs. In addition, I still have this problem when deploying this project to my own server.

**Comment by Charles-Leo** [comment] 2021-06-22 06:46
Every time I open the client with safari on my iPad, enter the IP address and port number. The first connection can be Keep connected about 10 seconds, and then click connect again, and it will be disconnected immediately.
obs-websocket version: 4.9.0
If you have a mobile device, you can try the following to see if this problem occurs. In addition, I still have this problem when deploying this project to my own server.

**Comment by Niek** [comment] 2021-08-09 10:46
I can't reproduce this, so I'm closing the issue. If it happens again, feel free to re-open.

**Closed by Niek** 2021-08-09 10:46 UTC
